@startuml CasosDeUsoPedidos
left to right direction
actor "Usuario" as U

rectangle "Sistema de Gestión de Pedidos" {
  usecase "Buscar pedido" as UC1
  usecase "Visualizar pedido" as UC2
  usecase "Buscar palabra o frase" as UC3
  usecase "Calcular totales" as UC4


  UC1 ..> UC2 : <<include>>
  UC2 ..> UC4 : <<include>>
  UC3 --|> UC1 : <<extend>>
}

U --> UC1
U --> UC3
U --> UC4
@enduml