@startuml SecuenciaBusquedaPedido
actor Usuario
participant "view:OrderView" as OV
participant "controller:OrderController" as OC
participant "searcher:Searcher" as S
participant "order:Order" as O

Usuario -> OV : clic en Search()
OV -> OC : searchOrder()

OC -> S : searchExactPhrase(id, listaIds)
S --> OC : boolean (encontrado)

alt id encontrado
    OC -> O : new Order(id)
    OC -> O : addArticulo(articulo)
    O --> OC : datos del pedido
    OC -> OV : displayOrder(order, rate)
    OV --> Usuario : muestra resultado
else id NO encontrado
    OC -> OV : displayErrorMessage("Pedido no encontrado")
    OV --> Usuario : muestra error
end
@enduml